version: 2
updates:
  - package-ecosystem: 'pip'
    directory: '/'
    schedule:
      interval: 'daily'
      time: '00:00'
      timezone: 'Europe/Amsterdam'
    target-branch: 'main'
    labels:
      - 'patch'
    reviewers:
      - 'bossan'
